new selenium
helensereda/QA21TEST pull request #2
Opened 2023-07-03 12:49 UTC by helensereda

2023-07-08 19:57 UTC, wildpioneer requested changes

2023-07-08 19:57 UTC, wildpioneer commented on src/test/java/SmokeTest_Homework.java
> +import org.testng.annotations.BeforeMethod;
pom.xml пустой и не содержит пакетов для Selenium

2023-07-08 19:57 UTC, wildpioneer commented on src/test/java/SmokeTest_Homework.java
> +        WebElement result = driver.findElement(By.id ("floor_cable_power"));
Зачем нужны эти переменные, если они затем не используюся?

2023-07-08 19:57 UTC, wildpioneer commented on src/test/java/SmokeTest_Homework.java
> +
Форматирование - 2 пустые строки это лишнее

2023-07-26 15:15 UTC, helensereda commented on src/test/java/SmokeTest_Homework.java
> +
спасибо, посмотрю,

2023-08-03 08:50 UTC, helensereda commented on src/test/java/SmokeTest_Homework.java
> +import org.testng.annotations.BeforeMethod;
Добавила

2023-08-03 09:26 UTC, helensereda commented on src/test/java/SmokeTest_Homework.java
> +        WebElement result = driver.findElement(By.id ("floor_cable_power"));
Да не нужны, убрала.

2023-08-28 11:39 UTC, wildpioneer commented
Закрыто

2023-08-28 11:39 UTC, closed without merging