Pageobject homework
helensereda/QA21TEST pull request #8
Opened 2023-07-24 15:22 UTC by helensereda

2023-08-02 14:26 UTC, wildpioneer requested changes

2023-08-02 14:26 UTC, wildpioneer commented on src/test/java/tests/EndToEndTest_hw.java
> +        Assert.assertTrue(
Не надо проверять каждый шаг - один тесто - одна конкретная проверка в конце теста

2023-08-02 14:26 UTC, wildpioneer commented on src/test/java/steps/FinishStep.java
> +      public CheckOutOverPage successFinish() {
Немного хромает разбиение на степы - степы должны группироваться по функциональности или сущностям , а не по страницам

2023-08-03 08:24 UTC, helensereda commented on src/test/java/steps/FinishStep.java
> +      public CheckOutOverPage successFinish() {
Не исправляю, посмотрю, спасибо.

2023-08-03 08:25 UTC, helensereda commented on src/test/java/tests/EndToEndTest_hw.java
> +        Assert.assertTrue(
Привет. Исправила вот так:
    @Test
    public void successTest()  {
                loginStep.successLogin(ReadProperties.username(), ReadProperties.password()).isPageOpened();
                addCartStep.successAddCart().isPageOpened();
                checkCartStep.successCheckCart().isPageOpened();
                addInfoStep.successInfo(ReadProperties.firstname(), ReadProperties.lastname(), ReadProperties.code()).isPageOpened();
                Assert.assertTrue(finishStep.successFinish().isPageOpened());
    }
}

2023-08-28 11:39 UTC, wildpioneer commented
Закрыто

2023-08-28 11:39 UTC, closed without merging