commit
helensereda/QA21TEST pull request #9
Opened 2023-07-26 15:11 UTC by helensereda

Саша смотрю сохраняются в домашку классы с предыдущей классной работы(сори)). Это надо перед тем как пушить что-то сначала  удалить не нужное из классной работы, а потом запушить, правильно понимаю?

2023-08-02 14:30 UTC, wildpioneer requested changes

2023-08-02 14:30 UTC, wildpioneer commented on src/test/java/tests/DynamicControlsTest.java
> +        WebElement buttonRemove  = waitService.waitForExists(By.xpath("//*[@id=\"checkbox-example\"]/button"));
Мне не нравиться такие локаторы - здесь лучше подойдет css "#checkbox-example button"

2023-08-02 14:30 UTC, wildpioneer commented on src/test/java/tests/UploadTest.java
> +        String pathToFile = "C:/Users/elena.sereda/IdeaProjects/QA21TEST/src/test/resources/picture.webp";
Такой путь здесь категорически не верный - он абсолютный и соответственно у меня не работает

2023-08-03 10:35 UTC, helensereda commented on src/test/java/tests/UploadTest.java
> +        String pathToFile = "C:/Users/elena.sereda/IdeaProjects/QA21TEST/src/test/resources/picture.webp";
Поправила без абсолютного пути.

   String pathToFile = UploadTest.class.getClassLoader().getResource("picture.webp").getPath();
        fileUploadElement.sendKeys(pathToFile.substring(1,pathToFile.length()));
        uploadPage.getButtonSubmit().click();
        Assert.assertEquals("picture.webp",uploadPage.getLabelUploaded().getText());

2023-08-03 10:38 UTC, helensereda commented on src/test/java/tests/DynamicControlsTest.java
> +        WebElement buttonRemove  = waitService.waitForExists(By.xpath("//*[@id=\"checkbox-example\"]/button"));
WebElement buttonRemove поправила.

2023-08-28 11:40 UTC, wildpioneer commented
Проверено

2023-08-28 11:40 UTC, closed without merging